requires = ["tox>=4"]
env_list = ["lint", "types", "tests", "py3.12", "py3.11", "py3.10", "py3.7"]

[env.lint]
description = "lint code"
skip_install = false
deps = ["black", "pylint", "setuptools"]
commands = [["black", { replace = "posargs", default = ["."], extend = true} ], ["pylint",  { replace = "posargs", default = ["."], extend = true}]]

[env.types]
description = "check types"
skip_install = false
deps = ["mypy", "setuptools", "types-setuptools"]
commands = [["mypy", { replace = "posargs", default = [".", "--exclude", "build", "--exclude", ".tox"], extend = true} ]]

[env.tests]
description = "run tests"
skip_install = false
deps = ["pytest"]
commands = [["pytest"]]

[gh.python]
"3.12" = ["py3.12", "lint", "types", "tests"]
"3.11" = ["py3.11", "lint", "types", "tests"]
"3.10" = ["py3.10", "lint", "types", "tests"]
"3.7" = ["py3.7", "lint", "types", "tests"]