name: Build, Test and publish

on:
    push:
        branches:
            - '*'

jobs:
    tox:
        name: Run Tox ${{ matrix.env }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                env:
                    - '3.12.8'
                    - '3.11.11'
                    - '3.10.16'
                    - '3.7.5'
                os:
                    - ubuntu-latest

        permissions:
            contents: read

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: '3.13'

            - name: install dependencies
              run: |
                  pip install -r requirements.txt -r dev-requirements.txt

            - name: Run tox checks
              run: tox
