name: Release
on:
    push:
        tags:
            - '*'
jobs:
    release:
        runs-on: ubuntu-24.04
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3

            - name: create release
              uses: ncipollo/release-action@v1
